@AnimalLibrary_HostAddress = http://localhost:5251/api


//GET ALL ANIMALS
GET {{AnimalLibrary_HostAddress}}/animals/

###

//GET ANIMAL BY ID
GET {{AnimalLibrary_HostAddress}}/animals/1

###


//CREATE ANIMAL
POST {{AnimalLibrary_HostAddress}}/animals/
Content-Type: application/json

{
  "name": "Elephant",
  "scientificName": "Loxodonta africana",
  "description": "The largest land animal",
  "imageUrl": "https://example.com/elephant.jpg",
  "groupId": 6,
  "habitatId": 2
}

###

//UPDATE ANIMAL
PUT {{AnimalLibrary_HostAddress}}/animals/1
Content-Type: application/json

{
  "name": "Elephant2",
  "scientificName": "Loxodonta africana",
  "description": "The largest land animal",
  "imageUrl": "https://example.com/elephant.jpg",
  "groupId": 6,
  "habitatId": 2
}

###

//DELETE ANIMAL
DELETE {{AnimalLibrary_HostAddress}}/animals/1

###

//GET ALL GROUPS
GET {{AnimalLibrary_HostAddress}}/groups

###

//GET GROUP BY ID
GET {{AnimalLibrary_HostAddress}}/groups/5

###

//CREATE GROUP 
POST {{AnimalLibrary_HostAddress}}/groups
Content-Type: application/json

{
  "name": "test"
}

###
//UPDATE GROUP
PUT {{AnimalLibrary_HostAddress}}/groups/8
Content-Type: application/json

{
  "name": "test3"
}

###
//DELETE GROUP
DELETE {{AnimalLibrary_HostAddress}}/groups/7

###

//GET ANIMALS OF A GROUP
GET {{AnimalLibrary_HostAddress}}/groups/6/animals

###

//GET HABITATS

GET {{AnimalLibrary_HostAddress}}/habitats

###

//GET HABITAT BY ID

GET {{AnimalLibrary_HostAddress}}/habitats/1

###

//CREATE HABITAT

POST {{AnimalLibrary_HostAddress}}/habitats
Content-type: application/json

{
  "name": "test"
}

###

//UPDATE HABITAT

PUT {{AnimalLibrary_HostAddress}}/habitats/6
Content-type: application/json

{
  "name": "test2"
}

###

//DELETE HABITAT

DELETE {{AnimalLibrary_HostAddress}}/habitats/6

###

//GET ANIMALS OF A HABITAT

GET {{AnimalLibrary_HostAddress}}/habitats/2/animals



